version: "3"

services:
  bili-helper:
    image: ghcr.io/maokwen/bili-helper:latest
    container_name: bili-helper
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Asia/Shanghai
      - CRON=false
    volumes:
      - $PWD/config:/config
    restart: unless-stopped

    