name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Package with Gradle
        run: gradle shadowJar -x test

      - name: ZIP files
        run: |
             -f ./build/libs/bili-helper-${{ env.RELEASE_VERSION }}-all.jar bili-helper-v${{ env.RELEASE_VERSION }}.jar
          zip bili-helper\ v${{ env.RELEASE_VERSION }}.zip bili-helper-v${{ env.RELEASE_VERSION }}.jar
          cp ./src/main/resources/config.json ./
          zip bili-helper\ v${{ env.RELEASE_VERSION }}.zip config.json
          zip bili-helper\ v${{ env.RELEASE_VERSION }}.zip -r docs/
          zip bili-helper\ v${{ env.RELEASE_VERSION }}.zip LICENSE

      # Docker Image 构建环境
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: vergilgao
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy docker files
        run: |
          pwd
          cp bili-helper-v${{ env.RELEASE_VERSION }}.jar app.jar
          cp ./src/main/resources/config.json config.json
          ls -l

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/maokwen/bili-helper:latest

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ env.RELEASE_VERSION }}
          release_name: bili-helper-v${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./bili-helper v${{ env.RELEASE_VERSION }}.zip
          asset_name: bili-helper-v${{ env.RELEASE_VERSION }}.zip
          asset_content_type: application/zip
